[2025-05-25T11:16:51.791+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_spark_modelisation_command scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-25T11:16:51.805+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_spark_modelisation_command scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-25T11:16:51.806+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-25T11:16:51.827+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_spark_modelisation_command> on 2025-05-24 00:00:00+00:00
[2025-05-25T11:16:51.840+0000] {standard_task_runner.py:57} INFO - Started process 519 to run task
[2025-05-25T11:16:51.845+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_spark_modelisation_command', 'scheduled__2025-05-24T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpchwq41lq']
[2025-05-25T11:16:51.850+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask run_spark_modelisation_command
[2025-05-25T11:16:51.928+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_spark_modelisation_command scheduled__2025-05-24T00:00:00+00:00 [running]> on host 65b298c9af88
[2025-05-25T11:16:52.049+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_spark_modelisation_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-24T00:00:00+00:00'
[2025-05-25T11:16:52.051+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-25T11:16:52.054+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-master python3 modelisation.py']
[2025-05-25T11:16:52.072+0000] {subprocess.py:86} INFO - Output:
[2025-05-25T11:16:55.824+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-25T11:16:55.825+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-25T11:16:56.236+0000] {subprocess.py:93} INFO - 25/05/25 11:16:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-25T11:17:00.625+0000] {subprocess.py:93} INFO - Spark session created successfully!
[2025-05-25T11:17:00.626+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-25T11:17:00.629+0000] {subprocess.py:93} INFO -   File "/opt/spark/work-dir/modelisation.py", line 226, in <module>
[2025-05-25T11:17:00.637+0000] {subprocess.py:93} INFO -     .csv(hdfs_path)
[2025-05-25T11:17:00.638+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^^
[2025-05-25T11:17:00.638+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/pyspark/sql/readwriter.py", line 740, in csv
[2025-05-25T11:17:00.639+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-05-25T11:17:00.640+0000] {subprocess.py:93} INFO -                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-25T11:17:00.640+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-25T11:17:00.641+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-05-25T11:17:00.641+0000] {subprocess.py:93} INFO -     raise converted from None
[2025-05-25T11:17:00.658+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: hdfs://namenode:9000/user/root/transactions/YYYY=2025/MM=05/DD=25/transaction_data.csv.
[2025-05-25T11:17:01.256+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-25T11:17:01.269+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-25T11:17:01.277+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_spark_modelisation_command, execution_date=20250524T000000, start_date=20250525T111651, end_date=20250525T111701
[2025-05-25T11:17:01.302+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task run_spark_modelisation_command (Bash command failed. The command returned a non-zero exit code 1.; 519)
[2025-05-25T11:17:01.327+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-25T11:17:01.358+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
