[2025-05-09T18:45:45.482+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T18:39:50.786554+00:00 [queued]>
[2025-05-09T18:45:45.492+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T18:39:50.786554+00:00 [queued]>
[2025-05-09T18:45:45.492+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-09T18:45:45.511+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_hive_command> on 2025-05-09 18:39:50.786554+00:00
[2025-05-09T18:45:45.519+0000] {standard_task_runner.py:57} INFO - Started process 6672 to run task
[2025-05-09T18:45:45.522+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-09T18:39:50.786554+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmpr23d07vg']
[2025-05-09T18:45:45.526+0000] {standard_task_runner.py:85} INFO - Job 118: Subtask run_hive_command
[2025-05-09T18:45:45.579+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T18:39:50.786554+00:00 [running]> on host d4afc872a8aa
[2025-05-09T18:45:45.661+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T18:39:50.786554+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T18:39:50.786554+00:00'
[2025-05-09T18:45:45.663+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T18:45:45.665+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            set -e  # Exit immediately on any error\n\n            # 1. Create metastore_db only if it doesn\'t exist\n            docker exec striming_processing-postgres-1 psql -U *** -d *** -tc "SELECT 1 FROM pg_database WHERE datname = \'metastore_db\'" | grep -q 1 || \\\n            docker exec striming_processing-postgres-1 psql -U *** -d *** -c "CREATE DATABASE metastore_db;" && \\\n\n            # 2. Check if Hive metastore schema already exists (check for VERSION table)\n            docker exec striming_processing-postgres-1 psql -U *** -d metastore_db -tc "SELECT 1 FROM pg_tables WHERE tablename = \'version\'" | grep -q 1 || \\\n            docker exec hive schematool -initSchema -dbType postgres && \\\n\n            # 3. Run Hive script\n            docker exec hive hive -f /home/query.hql\n        ']
[2025-05-09T18:45:45.677+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T18:45:47.654+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-05-09T18:45:47.654+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T18:45:47.655+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T18:45:47.656+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-05-09T18:45:47.657+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-05-09T18:45:48.658+0000] {subprocess.py:93} INFO - Metastore connection URL:	 jdbc:postgresql://postgres:5432/metastore_db
[2025-05-09T18:45:48.659+0000] {subprocess.py:93} INFO - Metastore Connection Driver :	 org.postgresql.Driver
[2025-05-09T18:45:48.659+0000] {subprocess.py:93} INFO - Metastore connection User:	 ***
[2025-05-09T18:45:48.871+0000] {subprocess.py:93} INFO - Starting metastore schema initialization to 2.3.0
[2025-05-09T18:45:48.872+0000] {subprocess.py:93} INFO - Initialization script hive-schema-2.3.0.postgres.sql
[2025-05-09T18:45:49.160+0000] {subprocess.py:93} INFO - Error: ERROR: relation "BUCKETING_COLS" already exists (state=42P07,code=0)
[2025-05-09T18:45:49.161+0000] {subprocess.py:93} INFO - org.apache.hadoop.hive.metastore.HiveMetaException: Schema initialization FAILED! Metastore state would be inconsistent !!
[2025-05-09T18:45:49.162+0000] {subprocess.py:93} INFO - Underlying cause: java.io.IOException : Schema script failed, errorcode 2
[2025-05-09T18:45:49.162+0000] {subprocess.py:93} INFO - Use --verbose for detailed stacktrace.
[2025-05-09T18:45:49.163+0000] {subprocess.py:93} INFO - *** schemaTool failed ***
[2025-05-09T18:45:49.196+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-09T18:45:49.207+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-09T18:45:49.213+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250509T183950, start_date=20250509T184545, end_date=20250509T184549
[2025-05-09T18:45:49.231+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 118 for task run_hive_command (Bash command failed. The command returned a non-zero exit code 1.; 6672)
[2025-05-09T18:45:49.244+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T18:45:49.269+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
