[2025-05-09T17:26:25.859+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:21:20.352965+00:00 [queued]>
[2025-05-09T17:26:25.867+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:21:20.352965+00:00 [queued]>
[2025-05-09T17:26:25.868+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-09T17:26:25.885+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_hive_command> on 2025-05-09 17:21:20.352965+00:00
[2025-05-09T17:26:25.892+0000] {standard_task_runner.py:57} INFO - Started process 3746 to run task
[2025-05-09T17:26:25.895+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-09T17:21:20.352965+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmpr0mzue1q']
[2025-05-09T17:26:25.898+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask run_hive_command
[2025-05-09T17:26:25.954+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:21:20.352965+00:00 [running]> on host d4afc872a8aa
[2025-05-09T17:26:26.056+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T17:21:20.352965+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T17:21:20.352965+00:00'
[2025-05-09T17:26:26.058+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T17:26:26.060+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hive -f query.hql']
[2025-05-09T17:26:26.071+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T17:26:28.098+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-05-09T17:26:28.099+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T17:26:28.100+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T17:26:28.100+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-05-09T17:26:28.100+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-05-09T17:26:29.398+0000] {subprocess.py:93} INFO - 
[2025-05-09T17:26:29.399+0000] {subprocess.py:93} INFO - Logging initialized using configuration in file:/opt/hive/conf/hive-log4j2.properties Async: true
[2025-05-09T17:26:31.550+0000] {subprocess.py:93} INFO - Could not open input file for reading. (File file:/home/query.hql does not exist)
[2025-05-09T17:26:57.483+0000] {subprocess.py:97} INFO - Command exited with return code 3
[2025-05-09T17:26:57.500+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 3.
[2025-05-09T17:26:57.506+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250509T172120, start_date=20250509T172625, end_date=20250509T172657
[2025-05-09T17:26:57.527+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task run_hive_command (Bash command failed. The command returned a non-zero exit code 3.; 3746)
[2025-05-09T17:26:57.558+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T17:26:57.587+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
