[2025-05-10T12:46:58.605+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-10T12:46:57.278778+00:00 [queued]>
[2025-05-10T12:46:58.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-10T12:46:57.278778+00:00 [queued]>
[2025-05-10T12:46:58.617+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-10T12:46:58.632+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_hive_command> on 2025-05-10 12:46:57.278778+00:00
[2025-05-10T12:46:58.638+0000] {standard_task_runner.py:57} INFO - Started process 908 to run task
[2025-05-10T12:46:58.641+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-10T12:46:57.278778+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpv9ts23lp']
[2025-05-10T12:46:58.645+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask run_hive_command
[2025-05-10T12:46:58.706+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-10T12:46:57.278778+00:00 [running]> on host e4f7794789ac
[2025-05-10T12:46:58.973+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-10T12:46:57.278778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-10T12:46:57.278778+00:00'
[2025-05-10T12:46:58.975+0000] {logging_mixin.py:151} INFO - üîç Checking if stimming_processing-postgres-1 is running...
[2025-05-10T12:46:59.024+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL.py", line 238, in run_hive_setup_or_query
    result = docker_exec(["psql", "-U", "airflow", "-c", "\\l"], container=container_name)
  File "/opt/airflow/dags/ETL.py", line 233, in docker_exec
    raise RuntimeError(f"Command {cmd} failed with exit code {result.returncode}: {result.stderr}")
RuntimeError: Command ['psql', '-U', '***', '-c', '\\l'] failed with exit code 1: Error: No such container: stimming_processing-postgres-1

[2025-05-10T12:46:59.039+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250510T124657, start_date=20250510T124658, end_date=20250510T124659
[2025-05-10T12:46:59.054+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task run_hive_command (Command ['psql', '-U', '***', '-c', '\\l'] failed with exit code 1: Error: No such container: stimming_processing-postgres-1
; 908)
[2025-05-10T12:46:59.097+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-10T12:46:59.113+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
